### ISSUE TITLE
Workaround for spacy.en.English() load time?

### ISSUE THREAD

**Issue by bittlingmayer** [spacy-io/spaCy#219]
Our file includes the folloiwing
```
from spacy.en import English
nlp = English()
```
The English constructor takes quite some time, depending on the machine.

Is there some workaround to speed it up, or something we're doing wrong?

**Comment by honnibal** [comment]
I'm working on replacing the model with a neural network, which should reduce load times and memory consumption. For now I think the bottle-neck is disk, so there's not much that can be done. On my bare-metal server the loading takes only 45s, but on AWS it takes about 2.5x that long.

Hopefully the NN model will be finished soon.

**Comment by bittlingmayer** [comment]
Thanks

Perhaps we will run it as a separate process, and just let our main prog talk to that one.

We have very similar numbers: on a CentOS machine it takes a few mins, on my MacBook a few dozen seconds.

**Comment by honnibal** [comment]
I'd love to have more insight into why it takes so long, and what the variance is due to. If you do any benchmarking, let me know! The part that loads the parser model is here:

https://github.com/honnibal/thinc/blob/master/thinc/model.pyx#L89

What we're doing is looping over successive calls to `Reader.read`:

https://github.com/honnibal/thinc/blob/master/thinc/model.pyx#L155

The memory is being allocated via this `cymem.Pool` class:

https://github.com/honnibal/cymem/blob/master/cymem/cymem.pyx#L31

The `model.load` code is called by spaCy here:

https://github.com/honnibal/spaCy/blob/master/spacy/syntax/parser.pyx#L85

You could verify that this part is indeed the slow part for you by loading `nlp = English(parser=False)`.

It'd be good to know whether it's indeed the disk reads that are slow, or whether it's something else that we could do more about, like the hash table insertions or the memory allocations.

But, don't spend too long on it :). As I said, I hope to be replacing this soon.

**Comment by bittlingmayer** [comment]
`nlp = English(parser=False)
To be honest, the one on our team battling this problem is learning Python at the same time, so we may not get to it.

**Comment by honnibal** [comment]
Solved!

On my laptop models now load in 13s, down from 90s.

This turned out to be a stupid problem =/. At some point in the many revisions of this code, I lost an important patch: before loading the model, I wasn't resizing the hash table! If the hash table is sized exactly, insertions are sequential. But resizing is very expensive, because we use open addressing and linear probing. When we resize the hash table, all keys must be reinserted!

There are 9 million entries in the table, so this is very expensive.

I feel stupid for not realising the loading time was extreme and there must be a problem. But, the important thing is: this will be fixed in the next version.

**Comment by bittlingmayer** [comment]
Great to hear, thanks!  Looking forward to trying it out.

**Comment by erbas** [comment]
Hey @honnibal, Great to see progress on the load time, when is it going to be released?

**Comment by henningpeters** [comment]
It just got released a few days ago. The latest spaCy (0.100.5) includes it. To be precise the loading time improvements come from thinc >= 5.

**Comment by erbas** [comment]
You legend!

**Comment by bittlingmayer** [comment]
Confirmed fixed, thanks :-)

**Comment by tpetmanson** [comment]
I know the ticket is already closed, but I want to say that great work!! Loading time on my server went from 45s down to 9s. I promise I won't spam again.
