### ISSUE TITLE
Using POS tagger on existing tokens

### ISSUE THREAD

**Issue by dschallis** [spacy-io/spaCy#245]
I've got a large amount of text that's already been tokenised into lists of strings by an external process.

Is there any way to pass that through Spacy's part of speech tagger? I can see that it can be called on a Doc object, but I can't see any way of creating that other than from using an English object's __call__ method on a string.

**Comment by honnibal** [comment]
Hey,

The docs should be clearer on this. You want:

```python

tokens = nlp.tokenizer.tokens_from_list(token_strings)
nlp.tagger(tokens)
```

If you want to apply preset tags, use:

```python

nlp.tagger.tag_from_strings(tokens, tag_strs)
```

The `doc.from_array` method is also useful for loading annotations.

**Comment by dschallis** [comment]
Thanks for that, knowing I can create tokens from a list of strings should help with a few things.

Is there anything else I need to do in order to initialise the tagger by the way? I'm currently getting `None` when using your code above, e.g.:

```
import spacy.en
NLP = spacy.en.English()

sent = 'This is a sentence .'
words = sent.split()
tokens = NLP.tokenizer.tokens_from_list(words)
print('Tokens:', tokens)
tags = NLP.tagger(tokens)
print('Tags:', tags)
```
outputs:
```
Tokens: This is a sentence . 
Tags: None
```

**Comment by honnibal** [comment]
The tagger, parser and NER all modify the tokens object in place. The design is optimized to use the annotations via the `Doc`, `Token` and `Span` objects, so that it's easy to hop between the different representations. This also allows us to store everything efficiently, and handle string<->integer encodings.

To get a list of strings do:

```[token.tag_ for token in doc]```

This produces the PTB-style tags like `VBZ`, `VBD`, etc. You can instead get the Google universal tags, at `token.pos_`. The integer encoded versions are at `token.tag` and `token.pos`, without the trailing underscore.

**Comment by dschallis** [comment]
Ah, thanks again, that works perfectly.
