### ISSUE TITLE
WordNet integration

### ISSUE THREAD

**Issue by knyghty** [spacy-io/spaCy#262]
I notice the WordNet corpus is included in spaCy, but I don't see any docs about how to interact with it.

In particular, I'd like to be able to look at synsets, hyponyms and hypernyms in a similar way to TextBlob: https://textblob.readthedocs.org/en/dev/quickstart.html#wordnet-integration

Can we do this already? If not, please consider this a feature request.

**Comment by honnibal** [comment]
This isn't currently supported, no. We only use WordNet for lemmatization at the moment.

What are you trying to get done? One reason I'm reluctant to support WordNet too deeply is that for most applications, WordNet isn't the solution I'd recommend. Distributional similarity models usually give better results.

**Comment by knyghty** [comment]
@honnibal, I'm looking into accommodation/mimicry. I'm trying to reimplement some code (currnently Perl) into something faster. It calculates semantic alignment between two people in a conversation by comparing a set of semantic tags (see Perl module here: http://search.cpan.org/~igorm/Lingua-EN-Semtags-Engine-0.01/lib/Lingua/EN/Semtags/Engine.pm), derived from WordNet data.

**Comment by honnibal** [comment]
I'd guess that word vectors would be better for that.

The zero-effort solution is the `.similarity()` method on `Token`, `Span` and `Doc` objects. If you need to, you can load new word vectors trained on data more similar to yours. The default vectors might not be ideal for you --- it's hard to say.

**Comment by knyghty** [comment]
I'm not really sure (I'm new to this field so I'm neither good at articulating my ideas nor at knowing what the best solutions are).

Firstly I'd like to replicate the original code faithfully and stick to the same method.

I also feel that comparing similarity of all words in a text with all words in another text is probably going to be much slower, and speed is an important factor here.

I understand though, that this is a fairly narrow use case, and understand if it's more effort than it's worth.

**Comment by honnibal** [comment]
I think you'll find the `.similarity()` method to be very fast. What it does is average the vectors for each word in the two documents, and then computes their cosine.  My guess would be that unless the WordNet-based approach is implemented very carefully, it will be much slower.

I understand what you mean about replicating the previous result. But replication alone isn't enough for us to consider supporting some functionality, as the end-state of that policy would be that the library ends up implementing and supporting every NLP technique ever developed.

Instead our policy is to offer only one way to do each thing, which we keep up-to-date with current best practice.

**Comment by knyghty** [comment]
@honnibal, after some reading I came across this paper: http://aclanthology.info/papers/align-disambiguate-and-walk-a-unified-approach-for-measuring-semantic-similarity

It seems to do what I want, and apparently performs very well in terms of accuracy. Do you still think that word vectors are a better solution here or might you be able to include this?

**Comment by honnibal** [comment]
That paper's nice, thanks. I hadn't seen it before.

I found updated work by the same authors, using Allen AI's Semantic Scholar: https://www.semanticscholar.org/paper/SensEmbed-Learning-Sense-Embeddings-for-Word-and-Iacobacci-Pilehvar/907d50fcab6dcd8716e3a6ce3f86dae0f60b9867

The updated work is important because the paper you mentioned was published *just* before word2vec was released. The word2vec algorithm made a big change to the semantic similarity landscape.

I've spent the last hour reading around the topic on semantic scholar. Over the last couple of years, attention has focussed more on lexical similarity tasks, which don't evaluate on the task you're interested in, which seems to be called "semantic textual similarity", a cousin of the paraphrase detection task. The 2014 task seems to be an update of the 2012 task, which Pilehvar et al (2012) evaluate on. The paper that scored best in 2014 is http://www.aclweb.org/anthology/S14-2098 , who conclude:

> We described SimCompass, the system we participated
> with at SemEval-2014 Task 3. Our experiments
> suggest that traditional knowledge-based
> features are cornered by novel corpus-based word
> meaning representations, such as word2vec, which
> emerge as efficient and strong performers under
> a variety of scenarios. We also explored whether
> context expansion is beneficial to the cross-level
> similarity task, and remarked that only when the
> context is particularly short, this enrichment is viable.
> However, in a meta-learning framework, the
> information permeating from a set of similarity
> measures exposed to varying context expansions
> can attain a higher performance than possible with
> individual signals. Overall, our system ranked first
> among 21 teams and 38 systems.

In other words: the paper which performed best at the follow-on evaluation from the one completed by the paper you cite explicitly concludes that WordNet-based methods are superseded by the newer word2vec-based models. This matches my previous understanding, which is why we've been designing spaCy towards support for word vectors, and not WordNet.

After reading a little further, I think this might lack a little bit of nuance. Many systems participating in subsequent related shared tasks used WordNet in combination with other features. But I'm still not sure how much WordNet contributed.

I think BabelNet, which is based on WordNet, seems like a very useful resource. But I'm more interested in the Wikipedia-oriented aspects of it. We'd like to support an ontology in future, especially for named entity linking. However, our focus will be on representing world knowledge, and less about things like lexical entailment. The current roadmap is to use distributional models for lexical semantics.

**Comment by knyghty** [comment]
Ok, I think you're probably right on this (for now :P). I'll close the ticket.

Thanks for giving me those leads too. I think I agree with you, in general, that there is not enough use in further WordNet integration right now to justify it.

**Comment by honnibal** [comment]
No worries. If you decide you definitely want WordNet and want to do some hacking, you can find some unfinished work on using WordNet with spaCy here: https://github.com/spacy-io/spaCy/tree/sense_unsupervised
