### ISSUE TITLE
Citation information

### ISSUE THREAD

**Issue by interrogator** [spacy-io/spaCy#272]
If we want to reference spaCy in a paper (and we do), there should be clear citation available, preferably with a DOI. Zenodo can create a DOI for a repository if there is no preferred paper. Thanks!

**Comment by honnibal** [comment]
Hey,

Personally in my own papers I like to cite algorithms and footnote implementations.

The parser can be cited as Honnibal and Johnson (2015):  http://www.emnlp2015.org/proceedings/EMNLP/bib/EMNLP162.bib . For the tagging algorithm I'd say that it's an averaged perceptron tagger following Collins (2002?), but with Brown cluster features as described by Koo and Collins (2008), and using greedy decoding. The named entity tagger is a bit harder to cite, because I haven't really documented the algorithm anywhere.

For the implementation I would specify the version and give the website. There are GitHub tags associated with each version, so you might prefer that. If you want to cite, you can use a DOI number --- that sounds fine.

I'd like to put a demo paper into this year's ACL. That would make a nice citation target.

**Comment by interrogator** [comment]
That's enough to go on for now. Thanks!
