### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by osamamukhtar11** [spacy-io/spaCy#274]
Installation failed with code error 1

![1](https://cloud.githubusercontent.com/assets/13291427/13249424/fe4a785a-da45-11e5-97a8-65bac59458ab.PNG)
![2](https://cloud.githubusercontent.com/assets/13291427/13249425/fe4d8180-da45-11e5-8c2d-f497acdb05e5.PNG)
![3](https://cloud.githubusercontent.com/assets/13291427/13249426/fe50b530-da45-11e5-84de-25fe58ecb9de.PNG)
![4](https://cloud.githubusercontent.com/assets/13291427/13249427/fe76932c-da45-11e5-94ed-7099ee93f2a9.PNG)

**Comment by henningpeters** [comment]
Strange, it looks like your MSVC environment doesn't contain some important definitions in limit.h. It's likely this is not a spaCy issue.

Some ideas what you could do are:

* Official Windows Python 3.4 binaries are compiled with Visual Studio 2010 (see https://docs.python.org/devguide/setup.html#windows). I think you always have to compile Python extension with the Visual Studio version that was used to compile Python. So either install VS 2010 or pip install in a Python 3.5 environment.

* Are you using plain Visual Studio 2015 or did you install any updates already? It seems MS changed builtin intrinsics into macros in limits.h with their update 1. Unfortunately, I can't find anything about this on the VS 2015 update 1 release note page (https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx). There is a workaround described at https://software.intel.com/en-us/articles/limits1120-error-identifier-builtin-nanf-is-undefined. For that you probably want to checkout and compile spaCy from source.

* Uninstall/reinstall Visual Studio

Btw: instead of posting screenshots its a bit easier to work with your error output if you copy&paste it.
