### ISSUE TITLE
Copying the model to another machine

### ISSUE THREAD

**Issue by zygmuntz** [spacy-io/spaCy#310]
I have downloaded the model (`python -m spacy.en.download`) on Windows. Now I'd like to transfer it to another machine, running Linux. Copying the `data` dir doesn't seem to do the trick. Is there a straightforward way to copy the model without downloading it again?

**Comment by henningpeters** [comment]
Hmm, that should work, but we haven't tested that. It's simply not a use-case we thought about yet, but we are not aware that we added anything in the design of the data packages that prevents copying the data dir between platforms. I assume you have good reasons for doing that, still could you please elaborate?

Are you sure you are copying the right path? You can get the data dir with `python -c "import sputnik; print(sputnik.default_data_path('spacy'))"`.

Also, what happens if you run `python -m spacy.en.download` on your target machine? Does it understand that the model is already installed?

**Comment by zygmuntz** [comment]
It has to do with using a mobile internet connection. I get the following error after copying `data/`:

	RuntimeError                              Traceback (most recent call last)
	/my/projects/spacy/transform.py in <module>()
		16 
		17 
	---> 18 nlp = spacy.en.English(parser=False, tagger=False, matcher=False, entity=False)
		19 
		20 transform( 'sample.txt', 'sample_out.txt' )

	/usr/local/anaconda/lib/python2.7/site-packages/spacy/language.pyc in __init__(self, data_dir, vocab, tokenizer, tagger, parser, entity, matcher, serializer, load_vectors, package, vectors_package)
		223         if package is None:
		224             if data_dir is None:
	--> 225                 package = util.get_package_by_name()
		226             else:
		227                 package = util.get_package(data_dir)

	/usr/local/anaconda/lib/python2.7/site-packages/spacy/util.pyc in get_package_by_name(name, via)
		28         raise RuntimeError("Model %s not installed. Please run 'python -m "
		29                            "spacy.en.download' to install latest compatible "
	---> 30                            "model." % name)
		31     except CompatiblePackageNotFoundException as e:
		32         raise RuntimeError("Installed model is not compatible with spaCy "

	RuntimeError: Model None not installed. Please run 'python -m spacy.en.download' to install latest compatible model.

When attempting to download (as root):

	# python -m spacy.en.download
	Model already installed. Please run 'python -m spacy.en.download --force' to reinstall.

**Comment by henningpeters** [comment]
Ok, understood.

I'd like you to run a few commands and share the output here to get a better view on your system:

1) run as root and as non-root:
`python -c "import spacy; print(spacy.about.__version__)"`

2) run as root and as non-root:
`python -c "import sputnik; print(sputnik.util.default_data_path('spacy'))"`

3) run as root and as non-root:
`python -m sputnik --name spacy find`

Generally it is recommended that you download/install spaCy and the model with the same user with which you later run code. Why? Because spaCy stores its model by default in the Python path which is sometimes different. Otherwise, it's also not unlikely you could end up with two different spaCy versions which complicates matter further.

**Comment by zygmuntz** [comment]
Yes, I installed spacy on Windows via conda, using the method provided in the instruction. Here's the output on Linux (spacy installed by root):

	# python -c "import spacy; print(spacy.about.__version__)"
	0.100.6

	$ python -c "import spacy; print(spacy.about.__version__)"
	0.100.6


	# python -c "import sputnik; print(sputnik.util.default_data_path('spacy'))"
	/usr/local/anaconda/lib/python2.7/site-packages/spacy/data

	$ python -c "import sputnik; print(sputnik.util.default_data_path('spacy'))"
	/usr/local/anaconda/lib/python2.7/site-packages/spacy/data


	# python -m sputnik --name spacy find
	[
	{
		"name": "en",
		"version": "1.0.9"
	}
	]

	$ python -m sputnik --name spacy find
	[]

As root, I can run this successfully:

	# python -c "import spacy; nlp = spacy.en.English(parser=False, tagger=False, matcher=False, entity=False)"

The script I have produces a segmentation fault afterwards, any idea why?

	import io
	import spacy

	from spacy.tokens.doc import Doc

	def transform( in_file, out_file ):   

		global nlp
	
		with io.open( out_file, 'w', encoding='utf8') as o_f:
			with io.open( in_file, 'rb' ) as i_f:
				for byte_string in Doc.read_bytes( i_f ):
					doc = Doc( nlp.vocab ).from_bytes( byte_string )
					doc.is_parsed = True
					o_f.write(transform_doc( doc )) 
					

	nlp = spacy.en.English( parser=False, tagger=False, matcher=False, entity=False )
					
	transform( 'sample.txt', 'sample_out.txt' )

**Comment by henningpeters** [comment]
Great, it seems we can conclude that copying model files over from Windows to Linux seems to work if the user on Linux is root.

Now, why doesn't this work as non-root? To me this looks like a permission problem.

In your setup both root and non-root share the same data directory: `/usr/local/anaconda/lib/python2.7/site-packages/spacy/data`. Depending on your umask setting files created by root can't be read by non-root.

Can you please check that all files under `/usr/local/anaconda/lib/python2.7/site-packages/spacy/data` are readable by non-root?

For the segmentation fault please open a separate ticket - it seems to be not related to original issue, correct?

**Comment by zygmuntz** [comment]
OK, thanks.
