### ISSUE TITLE
List index out of range error from GoldParse

### ISSUE THREAD

**Issue by ryangrimm** [spacy-io/spaCy#314]
I've been playing around with extending the named entities via the sample code from issue #187. Nearly everything is working fantastically. However, if I try to train a sentence with an "im" (or "Im" for that matter) I get an list index out of range error from GoldParse. For example, attempting to train the following sentence and it's associated BILOU format will throw the exception:

What is Jon Im Chan phone number
['O', 'O', 'B-XPERSON', 'I-XPERSON', 'L-XPERSON', 'O', 'O']

My only guess is that internally it's expanding Im to I'm and not adding in the extra tags, but that's just a wild guess.

**Comment by honnibal** [comment]
Hey,

Sorry for the delay getting to this.

The snippet of code I dropped into that issue does have a problem. The implementation of the `GoldParse` assumes that the length of all the parts of annotation you're providing are the same length. So, in this part of the snippet:

```python

    # Create a GoldParse object. This should have a better API...
    indices = tuple(range(len(doc)))
    words = [w.text for w in doc]
    tags = [w.tag_ for w in doc]
    heads = [0 for _ in doc]
    deps = ['' for _ in doc]
    # This is the only part we care about. We want BILOU format
    ner = ['U-ANIMAL', 'O', 'U-ANIMAL', 'O', 'B-ANIMAL', 'L-ANIMAL', 'O']
```

we need to make sure that all those lists are the same length. However you're getting the annotations, you should also supply the matching tokenization, in the `words` list.

If the tokenization produced by the tokenizer doesn't match the gold standard, the `GoldParse` class will do a Levenshtein alignment between the two, so that it can map the NER annotations onto the predicted tokens (with some missing labels). So, it's not such a disaster if you're getting tokenization problems. The model should still be able to cope.

If you want to fix the tokenization, you can replace the rule that is mapping `Im` to `I am` in your `specials.json`.  You can also force a particular tokenization by using the `tokens_from_list` method of `nlp.tokenizer`.  Another solution would be to use the `doc.merge()` or `span.merge()` methods to merge the tokens `I m` together, to fix the tokenization.

**Comment by ryangrimm** [comment]
Got it, thanks for the fantastically detailed explanation!
