### ISSUE TITLE
Segmentation fault from a script

### ISSUE THREAD

**Issue by zygmuntz** [spacy-io/spaCy#316]
The script I have produces a segmentation fault, any idea why?

	import io
	import spacy

	from spacy.tokens.doc import Doc

	def transform( in_file, out_file ):   

		global nlp

		with io.open( out_file, 'w', encoding='utf8') as o_f:
			with io.open( in_file, 'rb' ) as i_f:
				for byte_string in Doc.read_bytes( i_f ):
					doc = Doc( nlp.vocab ).from_bytes( byte_string )
					doc.is_parsed = True
					o_f.write(transform_doc( doc )) 

	nlp = spacy.en.English( parser=False, tagger=False, matcher=False, entity=False )

	transform( 'sample.txt', 'sample_out.txt' )

**Comment by henningpeters** [comment]
We should probably have a proper error message instead of a segmentation fault here. Thanks for notifiying us about this. In order to find out what the problem is I would like to reproduce the problem on my machine.

Just from this script it's unfortunately not clear what you are trying to do. Also the contents of `sample.txt` and a definition of `transform_doc` is missing. Could you please add some context?

**Comment by zygmuntz** [comment]
It appears that the problem has to do with the sample file (attached). It crashes python on Windows too.

[sample.txt](https://github.com/spacy-io/spaCy/files/199986/sample.txt)

**Comment by henningpeters** [comment]
`Doc.from_bytes()` expects a serialized `Doc` instance that was created from `Doc.to_bytes()`, see https://spacy.io/docs#doc-exportimport-frombytes and https://spacy.io/docs#doc-exportimport-tobytes.

You try to have `Doc.from_bytes()` read some ascii text.

If you are simply trying to parse the text just run:
```
import io
import spacy
nlp = spacy.load('en')
nlp(io.open('sample.txt', encoding='utf8').read())
```

**Comment by zygmuntz** [comment]
Ah, the joys of copy-paste. Thank you for clarifying this. 

Still, a message like "Attempted to read_bytes() from not-a-Doc-instance, terminating..." would be helpful. With another sample I just got a memory error.
