### ISSUE TITLE
Parse trees with multiple roots / disconnected trees

### ISSUE THREAD

**Issue by mrmutator** [spacy-io/spaCy#320]
I encountered a sentence that results in two disconnected parse trees and two roots (according to the `token.head is token` rule. I should not expect that behavior for any sentence, right?

Example:

```python
from spacy.en import English
parser = English()
string = u'there is just one specific item more that I would like to comment upon and then I will sit down , Mr. Speaker .'
result = parser(string)
for tok in result:
    print tok.i, tok.orth_, tok.head, tok.head is tok
print list(result.sents), len(list(result.sents))
```
Output:
```
0 there is  False
1 is is  True
2 just one  False
3 one item  False
4 specific item  False
5 item is  False
6 more sit  False
7 that like  False
8 I like  False
9 would like  False
10 like more  False
11 to comment  False
12 comment like  False
13 upon comment  False
14 and like  False
15 then sit  False
16 I sit  False
17 will sit  False
18 sit sit  True
19 down sit  False
20 , sit  False
21 Mr. Speaker  False
22 Speaker sit  False
23 . sit  False
[there is just one specific item more that I would like to comment upon and then I will sit down , Mr. Speaker .] 1
```

So, both tokens with index 1 and 18 are roots of the dependency tree and the entire string is parsed as one single sentence.

**Comment by honnibal** [comment]
This seems to be a case that the statistical model is handling poorly. In order to handle poorly punctuated text, spaCy uses the syntactic parse to help determine the sentence boundaries. On average this performs better, but in some situations you get unexpected errors like this.

We're working on ways to help you adapt spaCy's statistical models to your individual text types. We think this will make a big difference to its accuracy for each user.
