### ISSUE TITLE
Token Method bug ?

### ISSUE THREAD

**Issue by masscognition** [spacy-io/spaCy#323]
Using str(token) should return the equivalent of token.orth_.encode('utf8') . However when I use it I get back the equivalent of token.text_with_ws . My work around is unicode(token.orth_) .

Thanks for a great package !

**Comment by honnibal** [comment]
Thanks, fixed.

This sort of fix is nasty because it involves a change in semantics that might silently break users code. To help people ease the transition, I've added a toggle `spacy.tokens.token.keep_Token__str__semantics`. Passing True to this function sets a global switch that preserves the old semantics.

This function will disappear in a future versions --- it's just there to help people migrate their code.

**Comment by masscognition** [comment]
Thanks for the quick fix.
