### ISSUE TITLE
Problem importing Spacy in Spyder/IPython

### ISSUE THREAD

**Issue by ArdavanA** [spacy-io/spaCy#333]
Hi All, 

I have installed spacy within my virtual env. When I call it from python, it works fine. But when I call it from IPython or Spyder (which also uses IPython), it doesnt work and it gives me 2 different error messages. 
When I call it from IPython, I get something like

`/home/userdata/anaconda2/bin/../lib/./libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/lib/liblapack.so.3)`

and when I call it from Spyder, I get something like

`ImportError: /home/userdata/virtualenv1/lib/python2.7/site-packages/preshed/counter.so: undefined symbol: PyFPE_jbu`f

Thanks in advance

**Comment by henningpeters** [comment]
Managing different Python environments can be tricky, especially if like in your case you are mixing different Python distributions and package/environment managers. If possible, I would recommend you to streamline your setup a bit to reduce complexity.

But coming to the core the problem:

How did you install spaCy? I see anaconda in your path, did you install it via conda? I assume you installed it once and try to import it from different places by adapting the PYTHONPATH, is that correct?

What strikes me is that your first path is different from your second. Can you please explain your system setup a bit more?

spaCy doesn't depend on `libfortran` nor `liblapack` directly, hence I assume the error comes from a different dependency, maybe `numpy`? Is there a stack trace attached to the error you could share?

Because spaCy comes as a native extension it is only compatible with the Python interpreter for which it was installed. That means you won't be able to `import spacy` from, e.g., Python 3.5 if you installed it for Python 2.7. Also note that Python builds not only differ in the version numbers, but different build flags such as narrow/wide unicode support.

Which kinds of Python do you run in your different environments?

**Comment by ArdavanA** [comment]
Hi Peters,

Thanks a lot for your reply. I did some more research based on your suggestions and yes the problem was with the numpy library. So, I deleted all the numpy files and re installed it. I also deleted all the spacy files and re installled it, and it is working now on my normal environment (though it is not working on my virtual environment but I'll look at it at a later time and will content myself using the normal environment).

Kind regards

**Comment by thomwolf** [comment]
A few note on that issue which happened to me recently:
if you have import errors such as `undefined symbol: PyFPE_jbuf` when importing spacy in a clean newly conda environment, check that spacy is not importing Explosion's specific dependencies like [preshed](https://github.com/explosion/preshed), [thinc](https://github.com/explosion/thinc), [murmurhash](https://github.com/explosion/murmurhash) or [cymem](https://github.com/explosion/cymem) from the root environment (that might be compiled using a different python).
If it is the case, it is better to fully remove such dependencies from the root environment and work only in virtual environments.
You can see where spacy find these dependencies in the ouput of `pip install spacy`.
