### ISSUE TITLE
spaCy memver dependency not present in win-64 channel

### ISSUE THREAD

**Issue by piotr-teterwak** [spacy-io/spaCy#348]
Hey folks! 

Recently I tried installing both Windows 7 and Windows 8 machines via conda as follows:

```
.\conda.exe config --add channels spacy
.\conda.exe install spacy
```

I get errors stating that semver is not present in win-64 channels. Doing a binstar search, it looks like the package only exists for OS X and Linux.  

Furthermore, it appears that conda installations don't pick up pip installed packages(I tried installing semver via pip). 

I like installing via conda since installing the visual studio runtime libraries is a bit of a pain. 

Google's web search cache makes it seem like you guys were hosting semver previously in the spacy channel, but that no longer looks to be the case. 

Not sure if this is a conda or spacy error, but any ideas of getting around this are welcome!

Cheers!
-Piotr

**Comment by henningpeters** [comment]
Your analysis is spot on. What happened is that I saw that conda's defaults channel featuring a newer semver version than the one we provided and had assumed that because it's a pure python package it's safe to remove ours. For obvious reasons we don't want to become maintainer of all of spaCy's dependencies.

It seems though that the conda semver isn't packaged as pure python package and only provided for OS X and Linux.

Sorry for the trouble, I uploaded a new semver to the spacy channel. Please try again.

**Comment by piotr-teterwak** [comment]
Thanks for the quick response! I'll be trying it soon and will let you know!

Cheers!
-Piotr

**Comment by piotr-teterwak** [comment]
Issue resolved.
