### ISSUE TITLE
spaCy conda binaries require GLIBC 2.14

### ISSUE THREAD

**Issue by piotr-teterwak** [spacy-io/spaCy#355]
Hi all,

Currently spaCy is compiled against glibc 2.14. This makes spaCy incompatible with older versions of linux without building from source (or installing glibc 2.14, which can be tricky). If compiling conda binaries on an older machine is a low hanging fruit, this could increase usability. If not, free to close this issue with a will not fix.

**Comment by henningpeters** [comment]
Binary wheels for Linux are a long-standing issue in the Python community. We are following the recently set best-practices from https://www.python.org/dev/peps/pep-0513/ and build Linux wheels using the manylinux Docker container from https://github.com/pypa/manylinux. Not sure whether it's suitable for us to deviate from that.

**Comment by piotr-teterwak** [comment]
The pep-0513 standard and manylinux Docker container are both new to me. Thanks for sharing. It is getting at exactly the same issue I'm describing here. 

 From the manylinux README:

```
Therefore, if we want to make binaries that run on most Linux distros, we have to use a very old distro -- CentOS 5.
```

CentOS 5 is really old, and has a really old glibc, far older than the 2.14 that seems to be currently required (based on error messages trying to install on older machines). So I wouldn't go so far as saying you're doing something wrong, since I know very little about the processes used to build conda packages. Something is a bit fishy though. It may or may not be worth looking into.

**Comment by henningpeters** [comment]
I understand what you are saying - both, from a technical as well as from a usability perspective. The problem is just that its hard to build binary packages that work reliably across different Linux distros. While the manylinux PEP and Docker image was released fairly recently, the effort behind it is the culmination of a long discussion within the Python community over many years. Hence, it's probably smarter to follow than lead.

Regarding your concern linking to a very old glibc please see https://www.python.org/dev/peps/pep-0513/#versioning-of-core-shared-libraries

> The maintainers of the GNU C library follow a strict symbol versioning scheme for backward compatibility. This ensures that binaries compiled against an older version of glibc can run on systems that have a newer glibc .

We are no experts on this topic, though. If you want to have an expert opinion or dive deeper into this topic I suggest you get involved on the mailing list at https://groups.google.com/forum/#!forum/manylinux-discuss
