### ISSUE TITLE
optimising spacy loading/usage for POS tagging only, and doing specialized phrase chunking

### ISSUE THREAD

**Issue by SumeetSandhu** [spacy-io/spaCy#430]
Hi,
I have two questions.
Question#1 : I would like to use just the POS tagging for now, as it seems to be 100X faster than NLTK.
Can I disable loading of other portions (e.g. word vectors which are probably a big memory hog) to speed up loading and general execution?

Question#2: I would like to do custom phrase chunking (not the default noun_chunks). Are there any special hooks I can use beyond sticking the POS tags into 'for' loops ?

thanks

**Comment by honnibal** [comment]
Do:

```python

nlp = spacy.load('en', parser=False, entity=False)
```

To avoid loading the parser and NER. The vector loading API needs to be fixed.

For the custom chunking, check out how this works in `spacy/syntax/iterators.pyx`.

General tips for rule-writing sanity:

* Is the phrase you're interested in usually a constituent? That is, is it fully connected in the tree?

* If so, write rules that match the root of its subtree. This lets you write rules that match a particular token, and then use the `token.left_edge` and `token.right_edge` attributes to resolve a `Span` object.

* If your phrase isn't usually (or always) a constituent, can you fix the issue by retokenizing, `.merge()` method, probably using a pattern defined with the `Matcher` class? Usually if you have an "overhang", it's because the parser isn't doing what you want. It's sort of rare to want a contiguous sequence of tokens and *not* want them to be a constituent in the tree.

* To answer the questions above, use the displacy visualiser: `http://displacy.spacy.io`. This is the best way to figure out how the parser behaves.

Finally, I regret that it took me so long to get to this. I hope you managed to solve the issue in the meantime. I'm steadily working through the backlog of issues and getting better infrastructure set up.
