### ISSUE TITLE
Is it intended that StringStore always contains ''?

### ISSUE THREAD

**Issue by davechallis** [spacy-io/spaCy#431]
If so, is there some way to remove it, or avoid it being added? It would be nice when iterating through the stored strings not to have a special case for skipping this.

Also, it seems a bit counterintuitive that:

    >>> ss = spacy.strings.StringStore()
    >>> ss['foo']
    >>> print(len(ss))
    1
    >>> print(len(list(ss))
    2

**Comment by honnibal** [comment]
There are some design decisions in the `StringStore` that are arguably regrettable. I'll explain the way that it is now. Don't take this to mean it shouldn't/can't change --- I'm just explaining the internal consistency of the current state.

The `StringStore` maps any string to an integer, on *access*. So when you do `__getitem__` on the `StringStore`, you insert the string if it isn't there already. So the question is, what to do about the empty string? If the contract accepts "any string", I think the empty string should be handled. You don't want to raise on that value. On the other hand, the empty string *is* sort of special, and I don't like the idea of it receiving some arbitrary index. It's also good to have 0 reserved, so that there's a value that's recognisably special, in case we do want to return 0 for an "out of index" string.

For these reasons it made sense to me to ensure that the empty string maps to the index 0. Okay. But why return it through the iteration? Well, if we don't, then when we do `list(strings)`, and index into the list, we'll be off-by-one.

I think this is a situation where we're at a local maximum in the design-space. The result isn't that satisfying, but we have to make a move in multiple dimensions to solve the problem.

**Comment by davechallis** [comment]
Makes sense to me, thanks for clarifying the design decisions behind it. I've read the source .pyx for it now, so I can see what's intended.

By the way, how stable do you think the StringStore is at the moment? Was thinking of using it to replace some existing string->int mapping I've been using, but noticed that there was a warning in the docs about the file format being subject to change.

**Comment by honnibal** [comment]
Hmm.

I'll put it this way: it'll probably be some months before there's a significant change, and I think your code will be pretty easy to modify, even once that happens.

**Comment by davechallis** [comment]
Great, that's good enough for me :)
