### ISSUE TITLE
Custom matchers for named entities overlap existing named entities

### ISSUE THREAD

**Issue by lhawizy** [spacy-io/spaCy#478]
Hi,
I've created a new matcher for named entities. I've noticed that whenever there is an overlap between the entities this new matcher recognises and the existing named entities, i get broken text back. 
Currently I am creating a matcher and running it against the doc(similar to this example https://github.com/spacy-io/spaCy/issues/105)  instead of adding a new matcher.
The reason for this is that I am running this over a very large dataset and to create a new matcher each time and adding it to nlp.matcher may cause problems in the long run (as I am only using one instance of the English class across the whole run).
Is there a way of getting it to prefer one matcher over another?

**Comment by savkov** [comment]
Take a look at this issue [#241](https://github.com/spacy-io/spaCy/issues/241). It works for me, but I am still working with v 1.0.2. Not sure if this changed meanwhile.

**Comment by lhawizy** [comment]
Thank you.
Would this solution involve initialising an English() instance every time. I currently create a new matcher for each document I receive (its a workaround for extracting regular expression patterns, I get a regex to find the terms then pass them to the matcher). So in the case of hundreds of thousands of documents would I need to create new matcher and initialise an instance of English() ?

**Comment by savkov** [comment]
My interpretation would be that you need to create a new `Matcher` and assign it to `nlp.matcher` to swap it for each of your documents. Not sure what that involves internally in `spaCy`. It is not a particularly slow operation from what I've noticed.

**Comment by lhawizy** [comment]
Thanks will try it out and update!

**Comment by lhawizy** [comment]
So this method does end up calling  English() again and it does slow it down considerably
What I ideally would like is to reset back to the original matcher at the start of each run and add my custom matcher rules onto it.

Simple example:

# Initialise
def __init__(self):
    nlp = English()

def process(self, text):
    nlp.matcher = default_matcher
    nlp.matcher.add(new_matcher_rules)
    doc = nlp(text)

**Comment by honnibal** [comment]
I think you should probably just subclass `English`, and overwrite `English.__call__`. Then you can add an arbitry `my_matcher` class if you like.

It's not really well communicated at the moment, but the design has been to try to keep the `Language` class a very simple composition of its components. The idea is to avoid doing heavy lifting in these classes, so that you can easily write your own replacement.

The Language class is also pure Python, and you should feel free to do the usual loose dynamic-language stuff like adding a new field at runtime, like `nlp.my_matcher = Matcher()`. There shouldn't be a reason to monkey-patch, but if you need to...well, you could.

**Comment by honnibal** [comment]
In 1.0, the `Matcher` will return a list of `(ent_id, ent_type, start, end)` tuples --- it won't add the matched phrases to `doc.ents`. The user will have responsibility for that.

This will give the user responsibility for resolving overlaps, conflicts etc, however they want. I think this is a much better solution, because there's no reason why a single phrase shouldn't match multiple patterns.

**Comment by lhawizy** [comment]
Sorry just noticed the message that I have missed and thank you that is a much neater solution that would work really well for my case
