### ISSUE TITLE
how to add hashtags to the part of speech tagger

### ISSUE THREAD

**Issue by openfrdb** [spacy-io/spaCy#503]
Hey,

Great job on Spacy.

Trying to analyze twitter and other things that use hashtags.  Any way to add hashtags to the POS tagger?  i was hoping to be able to say anything following the # up to a whitespace will be considered a hashtag.  just don't know how to add it to the system.

Thanks!

**Comment by honnibal** [comment]
Good question. There's a few ways to do this.

Are the hash tags currently processed into one token by the tokenizer? If so, I would add a boolean flag to the `Vocab`, for `IS_HASH_TAG`. You do this by importing one of the available flag numbers as the name you want, e.g. `import FLAG63 as IS_HASHTAG`. Then you have a function which sets this flag, i.e. which defines whether a given orth string counts as a hashtag for your purposes. Finally, you want to attach this function to the `Vocab`, so that it gets called whenever a new `Lexeme` is added to the vocabulary, and its result is cached. This will mean that the tokenizer automatically sets this flag for you. You'll do this by either:

a) making an assignment like`nlp.vocab.get_lex_attrs[IS_HASHTAG] = my_is_hashtag_function`

b) creating a `Vocab` object with the new function assigned in its `get_lex_attrs` dict, and passing this object to `English.__init__`

c) Subclassing `English`, and overwriting the `default_get_lex_attrs` class method, so that your function is attached.

Remember to iterate over the vocabulary and set the flag of the existing tokens.

I should add a method `attach_flag_setter` or something to the `Vocab`. Tagging this issue as an enhancement and renaming it to remind me.

**Comment by openfrdb** [comment]
Thanks for the suggestion.   Unfortunately the tags seem to get parsed into a symbol and another word.  I'm using something like this to capture the tags and do what I need with the list:
`
    tag_found = False
    twitter_hash_tags = list()
    for token in doc:
        if ('#' in token.orth_ and tag_found is False):
            tag_found = True
	elif tag_found is True:
            twitter_hash_tags.append('#' + str(token.orth_))
            tag_found = False
`
Please let me know if I should create an issue for allowing the tagger to find hashtags (not sure if this is possible due to the usage of the Universal Tag Set scheme) or if there is another option besides what I have done above to get Spacy to recognize full hashtags.

Thanks for your prompt attention yesterday!!

**Comment by baily012** [comment]
Hi Matthew Honnibal, 

I am facing the same problem as @openfrdb to tokenize hashtags from tweets text. I don't know how can I tokenize e.g. "#Paris" as a whole using spaCy. I got "#" and "Paris" as two separate tokens. 

Tried to find a solution but unfortunately not much information about how to solve this problem.
It will be great if you could write an example of how to do. Thanks.

BR,
Lei

**Comment by csvance** [comment]
I was looking into adding a Tokenizer exception to keep the '#' together with the rest of the hashtag and classifying the hashtag as its own PoS without changing how I iterate through tokens. Could we use a regular expression here?

The exception match would be r'#([a-zA-Z0-9]+)'
The resulting token's ORTF would be r'#\1'

` tokenizer = English().Defaults.create_tokenizer(nlp)
    case = [{r'#([a-zA-Z0-9]+)': [{ORTH: r'#\1', POS: 'HASHTAG'}]}]
    tokenizer.add_special_case(case)`

However, I am not able to import the ORTH / POS from spacy.attrs (assume this changed with 2.0.0)

Will have to do some digging through the docs when I have more time.
