### ISSUE TITLE
Getting a list of possible dependency tree parses

### ISSUE THREAD

**Issue by scottyli** [spacy-io/spaCy#88]
I'm interested in seeing alternative parses.

Is there a method or instance variable that allows you to retrieve a list of possible dependency parse trees?

**Comment by honnibal** [comment]
I've periodically added and removed the beam-search functionality. It's currently dropped because the best transition-system for the greedy parser doesn't work very well with the beam.

I think this branch should be working: https://github.com/honnibal/spaCy/blob/beam/spacy/syntax/parser.pyx

I have two branches I'm working on at the moment, "gaz", and "de". "gaz" has some changes which are live on the displaCy demo, to allow you to step-through the parse: https://github.com/honnibal/spaCy/blob/gaz/spacy/syntax/parser.pyx

Depending on what you're doing the step-through functionality might be helpful.
